[pak]
name = "migrating-bitnami-to-bitnami-legacy"
version = "1.0.1"
description = """This rule book helps you migrate Bitnami Helm charts and container images from the bitnami repository to the bitnamilegacy repository.

This migration is necessary due to Bitnami's transition, effective August 28th, 2025, where existing images will be moved to the legacy repo"""
authors = ["Stakpak <team@stakpak.dev>"]
license = "MIT"
repository = "https://github.com/stakpak/paks"
path = "migrating-bitnami-to-bitnami-legacy"
tags = ["Bitnami", "Bitnami Legacy", "Bitnami Helm Charts"]
visibility = "public"

[contents]
[[contents.rulebooks]]
path = "rulebooks/migrating-bitnami-to-bitnami-legacy.md"
description = """This rule book helps you migrate Bitnami Helm charts and container images from the bitnami repository to the bitnamilegacy repository.

This migration is necessary due to Bitnami's transition, effective August 28th, 2025, where existing images will be moved to the legacy repo"""
tags = ["Bitnami", "Bitnami Legacy", "Bitnami Helm Charts"]
