[pak]
name = "infrastructure-cost-estimation"
version = "1.0.1"
description = """Help you discover how much you spend on AWS/GCP/Azure. This rulebook guides practitioners through proper cloud cost calculations, systematic resource discovery (via IaC analysis and live environment enumeration), authoritative pricing research and analysis/estimation."""
authors = ["Stakpak <team@stakpak.dev>"]
license = "MIT"
repository = "https://github.com/stakpak/paks"
path = "infrastructure-cost-estimation"
tags = ["cost", "cloud", "pricing", "cost optimization", "analysis", "aws", "gcp", "azure", "cloud spend", "finops"]
visibility = "public"

[contents]
[[contents.rulebooks]]
path = "rulebooks/infrastructure-cost-estimation.md"
description = """Help you discover how much you spend on AWS/GCP/Azure. This rulebook guides practitioners through proper cloud cost calculations, systematic resource discovery (via IaC analysis and live environment enumeration), authoritative pricing research and analysis/estimation."""
tags = ["cost", "cloud", "pricing", "cost optimization", "analysis", "aws", "gcp", "azure", "cloud spend", "finops"]
