[pak]
name = "nextjs-on-aws"
version = "1.0.1"
description = "This document compares various AWS deployment options for Next.js applications, analyzing costs, benefits, limitations, and providing recommendations based on different use cases."
authors = ["Stakpak <team@stakpak.dev>"]
license = "MIT"
repository = "https://github.com/stakpak/paks"
path = "nextjs-on-aws"
tags = ["nextjs", "aws", "deployment", "cost-analysis", "migration", "architecture"]
visibility = "public"

[contents]
[[contents.rulebooks]]
path = "rulebooks/nextjs-on-aws.md"
description = "This document compares various AWS deployment options for Next.js applications, analyzing costs, benefits, limitations, and providing recommendations based on different use cases."
tags = ["nextjs", "aws", "deployment", "cost-analysis", "migration", "architecture"]
