[pak]
name = "simple-deployment-on-vm"
version = "1.0.0"
description = "How to do simple but secure deployments using virtual machines on different cloud providers"
authors = ["Stakpak <team@stakpak.dev>"]
license = "MIT"
repository = "https://github.com/stakpak/paks"
path = "simple-deployment-on-vm"
keywords = ["aws", "deploy", "security", "dns", "ec2", "tls configuration"]
visibility = "public"

[contents]
[[contents.rulebooks]]
path = "rulebooks/simple-deployment-on-vm.md"
description = "How to do simple but secure deployments using virtual machines on different cloud providers"
tags = ["aws", "deploy", "security", "dns", "ec2", "tls configuration"]
